name: Reusable Deploy
on:
  workflow_call:
    inputs:
      artifacts-name:
        description: The name of deployable files
        required: false
        default: dist
        type: string
      outputs:
        results:
          description: The result of the deployment operation
          value:
jobs:
    deploy:
      runs-on: ubuntu-latest
      steps:
        - name: Get Code
          uses: actions/download-artifact@v3
          with:
            name: ${{ }}
        - name: Output Information
          run: echo "Deploying & Uploading ..."
        - name: set result output
          run: echo ":: set-output name=step-result
